@CecoBanATM.API_HostAddress = https://localhost:7267


POST {{CecoBanATM.API_HostAddress}}/api/v1/Tarjeta/CambioNIP/
Accept: application/json
Content-Type: application/json

{
    "Numero": "1529672056"
    ,"Codigo": "9281"
    ,"CodigoNuevo": "9081"
}
###


GET {{CecoBanATM.API_HostAddress}}/api/v1/Cuenta/ConsultaMonto/
Accept: application/json
Content-Type: application/json

{
    "Numero": "1529672056"
}


###


POST {{CecoBanATM.API_HostAddress}}/api/v1/Abonos/RegistraAbono/
Accept: application/json
Content-Type: application/json

{
    "Numero": "1529672056"
    ,"Monto": "0.5"
    ,"Tipo": "8"
    ,"TerminalKey": "cd71832f-73a1-4a97-84d9-c0d8200aac33"
    ,"Concepto": "Oxxo Suc. Aeropuerto"
}
